title: MONTERIAVENDE
email: tu-email@ejemplo.com
description: ""
baseurl: "" # el subdirectorio del sitio, por ejemplo /blog
url: "" # la URL base del sitio

# Permalinks personalizados para p√°ginas y posts
permalink: /:title/
collections:
  posts:
    permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed
